INSERT INTO KinhNghiems (NamKinhNghiem) VALUES
(N'Dưới 1 năm'),
(N'1 - 3 năm'),
(N'3 - 5 năm'),
(N'5 - 10 năm'),
(N'Trên 10 năm');

INSERT INTO KyNangMems (KNMem_name) VALUES
(N'Giao tiếp tốt'),
(N'Giỏi Ngoại Ngữ'),
(N'Tính toán nhanh'),
(N'Tư duy tốt'),
(N'Làm việc nhóm'),
(N'Giải quyết vấn đề'),
(N'Tinh thần trách nhiệm'),
(N'Sáng tạo'),
(N'Quản lý thời gian'),
(N'Tự học và tự nâng cấp kỹ năng');

INSERT INTO TruongDaiHocs (TruongDaiHoc_name) VALUES
(N'Đại học Quốc gia Hà Nội'),
(N'Đại học Quốc gia Thành phố Hồ Chí Minh'),
(N'Đại học Bách Khoa Hà Nội'),
(N'Đại học Khoa học Xã hội và Nhân văn TP. Hồ Chí Minh'),
(N'Đại học Ngoại Thương'),
(N'Đại học Kinh tế Quốc dân'),
(N'Đại học Sư phạm Hà Nội'),
(N'Đại học Công nghệ'),
(N'Đại học Y Hà Nội'),
(N'Đại học Luật Hà Nội'),
(N'Đại học Bách khoa Đà Nẵng'),
(N'Đại học Sư phạm Đà Nẵng'),
(N'Đại học Đà Nẵng'),
(N'Đại học Khoa học Tự nhiên TP. Hồ Chí Minh'),
(N'Đại học Sư phạm TP. Hồ Chí Minh'),
(N'Đại học Y Dược TP. Hồ Chí Minh'),
(N'Đại học Nông Lâm TP. Hồ Chí Minh'),
(N'Đại học Y Dược Hà Nội'),
(N'Đại học Công nghệ Thông tin và Truyền thông');

INSERT INTO ThanhPhos (ThanhPho_name) VALUES
(N'Hà Nội'),
(N'Hồ Chí Minh'),
(N'Hải Phòng'),
(N'Cần Thơ'),
(N'Đà Nẵng'),
(N'Biên Hòa'),
(N'Nha Trang'),
(N'Bắc Giang'),
(N'Vũng Tàu'),
(N'Huế'),
(N'Long Xuyên'),
(N'Thái Nguyên'),
(N'Quy Nhơn'),
(N'Rạch Giá'),
(N'Thái Bình'),
(N'Hòa Bình'),
(N'Bắc Ninh'),
(N'Vinh'),
(N'Bảo Lộc'),
(N'Tam Kỳ'),
(N'Thanh Hóa'),
(N'Lào Cai'),
(N'Nam Định'),
(N'Yên Bái'),
(N'Phan Thiết'),
(N'Hưng Yên'),
(N'Vĩnh Long'),
(N'Bạc Liêu'),
(N'Kiên Giang'),
(N'Tuy Hòa'),
(N'Đồng Hới'),
(N'Hà Tĩnh'),
(N'Buôn Ma Thuột'),
(N'Ninh Bình'),
(N'Phủ Lý'),
(N'Cà Mau'),
(N'Tây Ninh'),
(N'Hải Dương'),
(N'Bắc Kạn'),
(N'Bến Tre'),
(N'Quảng Ngãi'),
(N'Đồng Tháp'),
(N'Thủ Dầu Một'),
(N'Hà Giang'),
(N'Sóc Trăng'),
(N'Trà Vinh'),
(N'Kon Tum'),
(N'Đồng Xoài'),
(N'Bà Rịa'),
(N'Hậu Giang'),
(N'Sơn La'),
(N'Điện Biên Phủ'),
(N'Bắc Ninh'),
(N'Phan Rang-Tháp Chàm'),
(N'Hà Tiên'),
(N'Thái Bình'),
(N'Vĩnh Yên'),
(N'Hòa Bình'),
(N'Hà Nam'),
(N'Lạng Sơn'),
(N'Hải Phòng'),
(N'Sài Gòn'),
(N'An Giang');

INSERT INTO ViTriCongViecs (ViTriCongViec_name) VALUES
(N'Lập trình viên'),
(N'Kỹ sư phần mềm'),
(N'Nhân viên kinh doanh'),
(N'Quản lý dự án'),
(N'Chuyên viên tài chính'),
(N'Kế toán viên'),
(N'Nhân viên hành chính');


INSERT INTO chuyenNganhs(ChuyenNganh_name) VALUES
(N'Khoa học máy tính'),
(N'Kỹ thuật phần mềm'),
(N'Kinh doanh quốc tế'),
(N'Quản trị kinh doanh'),
(N'Kế toán'),
(N'Quản lý nhân sự'),
(N'Marketing'),
(N'Tài chính ngân hàng'),
(N'Kinh tế quốc tế'),
(N'Kỹ thuật điện tử viễn thông'),
(N'Kỹ thuật ô tô'),
(N'Y học'),
(N'Y học cổ truyền'),
(N'Luật kinh doanh'),
(N'Kỹ thuật cơ điện tử'),
(N'Sư phạm Tiếng Anh'),
(N'Công nghệ thông tin'),
(N'Quản lý công nghiệp'),
(N'Tâm lý học'),
(N'Thiết kế đồ họa');
